### ISSUE TITLE
Invalid links to Discord channel

### ISSUE THREAD

**Issue by nicoleSosa** [ossd-s23/TitleBarColoring#10]
When I tried to join the Discord channel through the links provided in the README file's contributing section and the CONTRIBUTING document's section guideline for adding new functions, I was redirected to an invite invalid page which mentioned that this invite link might be expired or I don't have permission to join. I am unsure if this is only on my end.

**Comment by ROMEEZHOU** [comment]
Hi thank you for reaching out! Could you please upload a screenshot of the invalid page? We have asked other people to try and there seemed to be no problem

**Comment by nicoleSosa** [comment]
Sure! This is what shows up when I try to use the discord link. 

<img width="1440" alt="Screen Shot 2023-02-18 at 10 06 38 PM" src="https://user-images.githubusercontent.com/83420994/219909947-83de5ed7-cde2-49a5-9807-d7e360ace63a.png">

**Comment by ROMEEZHOU** [comment]
Can you try this one, I created a new invitation https://discord.gg/G6PNMHJc

**Comment by nicoleSosa** [comment]
This one works! Thank you. 

<img width="1440" alt="Screen Shot 2023-02-18 at 10 25 30 PM" src="https://user-images.githubusercontent.com/83420994/219911854-0c1eca46-35eb-40c2-ac79-1847cba12d4d.png">
